import * as z from "zod";

export const createPostSchema = z.object({
  name: z.string(),
  type: z.enum([
    "PLATFORM",
    "WINDOW",
    "ADS",
    "TRAIN_SCHEDULE_ARRIVAL",
    "TRAIN_SCHEDULE_DEPARTURE",
  ]),
  windowNumber: z.number().optional(),
  trainSchedulesId: z.string().optional(),
  backgroundType: z.enum(["COLOR", "IMAGE", "VIDEO"]),
  backgroundColor: z.string().optional(),
  backgroundImage: z.string().optional(),
  backgroundText: z.string().optional(),
  backgroundTextEng: z.string().optional(),
  backgroundTextEnable: z.boolean().optional(),
  backgroundTextEngEnable: z.boolean().optional(),
  backgroundTextFont: z.string().optional(),
  backgroundTextFontsize: z.number().optional(),
  backgroundTextColor: z.string().optional(),
  postMedia:
    typeof File !== "undefined"
      ? z.instanceof(File).optional()
      : z.unknown().optional(),
  backgroundVideo: z.string().optional(),
  textSliderThEnable: z.boolean().optional(),
  textSliderEngEnable: z.boolean().optional(),
  textSliderBackgroundColor: z.string().optional(),
  textSliderColor: z.string().optional(),
  textSliderFont: z.string().optional(),
  textSliderFontsize: z.number().optional(),
  textSliderSpeed: z.number().optional(),
  textSliderTh: z.string().optional(),
  textSliderEng: z.string().optional(),
  destinationFont: z.string().optional(),
  destinationFontsize: z.number().optional(),
  destinationColor: z.string().optional(),
  windowNumberFont: z.string().optional(),
  windowNumberFontsize: z.number().optional(),
  windowNumberColor: z.string().optional(),
  trainTypeFont: z.string().optional(),
  trainTypeFontsize: z.number().optional(),
  trainTypeColor: z.string().optional(),
  platformFont: z.string().optional(),
  platformFontsize: z.number().optional(),
  platformColor: z.string().optional(),
  categoryFont: z.string().optional(),
  categoryFontsize: z.number().optional(),
  categoryColor: z.string().optional(),
  lateTimeFont: z.string().optional(),
  lateTimeFontsize: z.number().optional(),
  lateTimeColor: z.string().optional(),
  trainTimeFont: z.string().optional(),
  trainTimeFontsize: z.number().optional(),
  trainTimeColor: z.string().optional(),
  topicFont: z.string().optional(),
  topicFontsize: z.number().optional(),
  topicColor: z.string().optional(),
  roundTrip: z.string().optional(),
});

export type CreatePostFormValues = z.infer<typeof createPostSchema>;
